/**
* Payment Gateway
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: 1.0.0-oas3
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.ccommercepayment.models

import com.ccommercepayment.models.CardData
import com.ccommercepayment.models.CardPaymentContextData

import com.squareup.moshi.Json
/**
 * 
 * @param context 
 * @param card 
 */

data class StoredPaymentMethodRequest (
    @Json(name = "context")
    val context: CardPaymentContextData? = null,
    @Json(name = "card")
    val card: CardData? = null
) 



